version: "3.1"
services:

    mysql:
        image: mysql:8.0
        container_name: spotify-library-mysql
        working_dir: /app
        volumes:
            - .:/app
        environment:
            - MYSQL_ROOT_PASSWORD=spotify-library
            - MYSQL_DATABASE=spotify-library
            - MYSQL_USER=spotify-library
            - MYSQL_PASSWORD=spotify-library
        ports:
            - "33060:3306"

    webserver:
        image: nginx:alpine
        container_name: spotify-library-webserver
        working_dir: /app
        volumes:
            - .:/app
            - ./build/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8085:80"

    php-fpm:
        build: build/docker/php-fpm
        container_name: spotify-library-php-fpm
        working_dir: /app
        volumes:
            - .:/app
            - ./build/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

