parameters:
    app.spotify.client_id: '%env(SPOTIFY_APP_CLIENT_ID)%'
    app.spotify.client_secret: '%env(SPOTIFY_APP_CLIENT_SECRET)%'
    app.spotify.callback_url: '%env(SPOTIFY_APP_CALLBACK_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    SpotifyWebAPI\SpotifyWebAPI: ~

    SpotifyWebAPI\Session:
        arguments:
            - '%app.spotify.client_id%'
            - '%app.spotify.client_secret%'
            - '%app.spotify.callback_url%'

    App\Service\SpotifyAuthService:
        arguments:
            - '@SpotifyWebAPI\Session'
            - '@security.helper'
            - '@doctrine.orm.entity_manager'
