parameters:
    app.spotify.client_id: '%env(SPOTIFY_APP_CLIENT_ID)%'
    app.spotify.client_secret: '%env(SPOTIFY_APP_CLIENT_SECRET)%'
    app.spotify.callback_url: '%env(SPOTIFY_APP_CALLBACK_URL)%'

    app.mail.sender.address: '%env(APP_MAIL_SENDER_ADDRESS)%'
    app.mail.sender.name: '%env(APP_MAIL_SENDER_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\EmailService:
        arguments:
            - '%app.mail.sender.address%'
            - '%app.mail.sender.name%'

    SpotifyWebAPI\SpotifyWebAPI: ~

    spotify_web_api.private_session:
        class: SpotifyWebAPI\Session
        arguments:
            - '%app.spotify.client_id%'
            - '%app.spotify.client_secret%'
            - '%app.spotify.callback_url%'

    spotify_web_api.public_session:
        class: SpotifyWebAPI\Session
        arguments:
            - '%app.spotify.client_id%'
            - '%app.spotify.client_secret%'

    App\Service\SpotifyClient:
        arguments:
            - '@SpotifyWebAPI\SpotifyWebAPI'
            - '@App\Repository\UserRepository'
            - '@spotify_web_api.public_session'
            - '@spotify_web_api.private_session'

    App\Service\SpotifyAuthService:
        arguments:
            - '@spotify_web_api.private_session'
            - '@security.helper'
            - '@doctrine.orm.entity_manager'
